# --- Style extraction prompts ------------------------------------------------

LOW_STYLE_EXTRACTION_SYSTEM_PROMPT = (
    "You analyze a translated novel chapter and extract a short Writing Style Profile.\n"
    "\n"
    "Focus only on reusable translation decisions that apply to the novel as a whole.\n"
    "Do not mention character names, locations, story events, or chapter-specific details.\n"
    "- narration formality\n"
    "- dialogue formality\n"
    "- pacing (slow, moderate, fast)\n"
    "- title handling\n"
    "- honorific handling\n"
    "- terminology localization\n"
    "\n"
    "Output 5-10 short bullet points.\n"
    "\n"
    "Each bullet must be a direct instruction beginning with a verb:\n"
    "- Use...\n"
    "- Keep...\n"
    "- Maintain...\n"
    "- Translate...\n"
    "- Preserve...\n"
    "\n"
    "Do not explain why.\n"
    "Do not discuss plot, characters, or events.\n"
    "Keep the entire profile under 100 words."
)

STYLE_EXTRACTION_SYSTEM_PROMPT = (
    "You are a linguistic analyst and literary editor. You analyze a previously translated "
    "novel chapter and extract a concise, reusable Writing Style Profile.\n"
    "\n"
    "Ignore the plot, characters, and events entirely. Instead, focus on HOW the text is "
    "written:\n"
    "\n"
    "1. PROSE PATTERNS: sentence length and rhythm (short/punchy vs long/descriptive), "
    "narrative pacing, paragraph structure.\n"
    "2. VOCABULARY & REGISTER: archaic, formal, conversational, or mixed? How literary vs "
    "modern is the word choice?\n"
    "3. DIALOGUE TONE: how different characters speak (do elders use formal English? do "
    "younger characters use modern slang?). Dialogue tag style.\n"
    "4. NARRATIVE PERSPECTIVE: first person, third person limited, third person omniscient? "
    "How close is the POV to the character's thoughts?\n"
    "5. LOCALIZATION PREFERENCES: are honorifics left intact (e.g. '-san', 'Shixiong'), "
    "capitalized literally ('Elder', 'Senior Brother'), or heavily localized? Are titles "
    "and terms left in the source language or translated?\n"
    "6. IMAGERY & DESCRIPTION: level of sensory detail, metaphor density, action scene pacing.\n"
    "\n"
    "Output a concise, structured markdown guide (150-300 words maximum) that another AI "
    "translator can use as a system instruction to replicate this writing style exactly. "
    "Write it as direct instructions ('Use ...', 'Maintain ...', 'Keep ...'), not as "
    "observations ('The text uses ...'). No plot summary, no character names, no code fences."
)
